server:
  port: 10010
logging:
  level:
    cn.xxxx: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    # gateway配置
    gateway:
      # 路由配置
      routes:
        - id: user-service # 路由id，自定义，必须唯一
#          uri: http://localhost:8081     # 匹配后提供服务的路由地址
          uri: lb://userservice # 路由的目标地址 lb就是负载均衡 后面跟的是服务名称
          predicates: # 断言规则，用于路由规则的匹配
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
#            - After=2022-04-07T17:42:47.789-07:00[Asia/Shanghai]
#            - Cookie=chocolate, ch.p
#            - CheckAuth=zhangsan1 # 自定义断言工厂
          filters:
#            - StripPrefix=1 # 转发之前去掉第一层过滤器
            - AddRequestHeader=X-Request-red, blue
            - AddRequestParameter=red, blue
            - AddResponseHeader=X-Response-Red, Blue
#            - PrefixPath=/user-service
#            - RedirectTo=302, https://spring.io/
            - CheckAuth=zhangsan
      default-filters:
        - AddRequestHeader=Truth, admin
